feat: enable launcher via linux app image
opendexnetwork/opendex-desktop pull request #20
Opened 2021-02-17 15:48 UTC by maybeast

2021-02-17 17:46 UTC, stackingcats requested changes
Looks good in general. Just some minor things.
Also, let's handle the case when the user has not been added to docker group and gets `permission denied`.

2021-02-17 17:46 UTC, stackingcats commented on public/ipc.js
> +    return `BRANCH=${BRANCH} NETWORK=${NETWORK} ${LAUNCHER} stop`;
Here we could also use the nice `*_LAUNCHER_COMMAND` variables.

2021-02-17 17:46 UTC, stackingcats commented on src/common/dockerUtil.ts
> +          "'docker' is not recognized as an internal or external command"
When executing `docker-compose version` on an Ubuntu machine without docker-compose, I get a response starting with `Command 'docker-compose' not found`.

2021-02-17 17:46 UTC, stackingcats commented on src/common/dockerUtil.ts
> +      logError("Error checking Docker installed status:", e);
This should probably refer to Docker-Compose, not Docker?

2021-02-17 21:46 UTC, maybeast commented
@stackingcats your feedback is addressed + `DockerPermissionDenied` screen was handled in order to point users to the https://docs.docker.com/engine/install/linux-postinstall/ docs.

2021-02-18 09:56 UTC, stackingcats requested changes
Added two suggestions to improve the text in the `DockerPermissionDenied` screen.

2021-02-18 09:56 UTC, stackingcats commented on src/setup/create/DockerPermissionDenied.tsx
> +    },
```suggestion
    },
    stepsContainer: {
      width: "657px",
    },
```

2021-02-18 09:56 UTC, stackingcats commented on src/setup/create/DockerPermissionDenied.tsx
> +      </Grid>
```suggestion
      <Grid item container direction="column">
        <Grid item container justify="center">
          <Typography variant="h6" component="h2" align="center">
            Docker permission denied. Please follow the post-installation steps
            and:
          </Typography>
        </Grid>
        <Grid item container justify="center">
          <ul className={classes.stepsContainer}>
            <li>Log out and log back in</li>
            <li>Restart your machine if still seeing this</li>
          </ul>
        </Grid>
      </Grid>
```

2021-02-18 13:17 UTC, stackingcats approved these changes
LGTM :+1:

2021-02-18 13:33 UTC, merged